name: Makefile CI

on: push
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: make setup_tc

    - name: Run check
      run: make release_tc

